version: '3.8'

services:
  web:
    build: .
    ports:
      # Mapea el puerto 8001 del host al 8000 del contenedor
      - '8001:8000'
    volumes:
      # Monta el código local en el contenedor para desarrollo (recarga automática)
      - ./app:/app/app
    environment:
      # DATABASE_URL se construye usando variables del .env
      DATABASE_URL: mysql+pymysql://${DB_USERNAME}:${DB_PASSWORD}@db:3306/${DB_NAME}
    depends_on:
      - db
    # Comando para desarrollo con recarga (sobrescribe CMD en Dockerfile)
    command:
      [
        'uvicorn',
        'app.main:app',
        '--host',
        '0.0.0.0',
        '--port',
        '8000',
        '--reload',
      ]

  db:
    # Usar una imagen de MySQL compatible con ARM64
    image: mysql:8.0
    # Alternativamente, puedes forzar la plataforma si es necesario:
    # platform: linux/arm64/v8
    environment:
      # Usa variables del .env
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      # Persistencia de datos de la base de datos
      - mysql_data:/var/lib/mysql
    ports:
      # Mapea el puerto definido en .env al 3306 del contenedor
      - '${DB_PORT}:3306'
    # Asegura que MySQL 8 use autenticación nativa compatible con drivers como pymysql
    command: ['--default-authentication-plugin=mysql_native_password']

volumes:
  mysql_data:
